<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MetroToolKits.Foundation.Building</RootNamespace>
    <AssemblyName>MetroToolKits.Foundation.Building</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\MetroToolKits.Foundation.Core\MetroToolKits.Foundation.Core.csproj" />
  </ItemGroup>
</Project>
