<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>MetroToolKits.Foundation.Cad.Layering</RootNamespace>
    <AssemblyName>MetroToolKits.Foundation.Cad.Layering</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="acdbmgd">
      <HintPath>..\..\..\build\References\acdbmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="acmgd">
      <HintPath>..\..\..\build\References\acmgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="accoremgd">
      <HintPath>..\..\..\build\References\accoremgd.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>
